site_name: Pacemaker Clustering
site_url: https://github.com/SparkChaos/Pacemaker
site_description: A pacemaker clustering strap script
site_author: Richard Karus

nav:
    - Home: index.md
    - Pacemaker Clustering Build:
        - Prerequisites for Pacemaker: pacemaker-build/prerequisites-for-pacemaker.md
        - Cluster Setup using Pacemaker: pacemaker-build/cluster-setup-for-pacemaker.md
        - Creating LVM Resources in Pacemaker: pacemaker-build/creating-lvm-resources-in-pacemaker.md
        - Creating a Virtual IP Resource in Pacemaker: pacemaker-build/creating-a-virtual-ip-resource-in-pacemaker.md
        - Creating a new Power-fencing Resource in Pacemaker: pacemaker-build/creating-a-new-power-fencing-resource-in-pacemaker.md
    - Managing HA Services in Pacemaker:
        - Configure Apache HA in Pacemaker: pacemaker-manage/configure-apache-ha-in-pacemaker.md
        - Configure Oracle HA in Pacemaker: pacemaker-manage/configure-oracle-ha-in-pacemaker.md

plugins:
    - search
