site_name: Pacemaker Clustering
site_url: https://github.com/SparkChaos/Pacemaker
site_description: A pacemaker clustering strap script
site_author: Richard Karus

nav:
    - Home: index.md
    - Pacemaker Clustering Build:
        - Building the Cluster: pacemaker-build/Build.md
    - HA Services in Pacemaker:
        - Adding Services: pacemaker-manage/Manage.md

plugins:
    - search
